package generator

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	goParser "go/parser"
	"go/token"
	"path/filepath"
	"regexp"
	"strings"

	"github.com/restartfu/rune/internal/parser"
)

func Generate(file *parser.File, sourcePath string) ([]byte, error) {
	var b bytes.Buffer
	goGeneratePath := filepath.ToSlash(sourcePath)

	fmt.Fprintln(&b, "// Code generated by rune; DO NOT EDIT.")
	fmt.Fprintf(&b, "//go:generate rune generate %s\n", goGeneratePath)

	if len(file.Pieces) == 0 {
		fmt.Fprintf(&b, "package %s\n\n", file.PackageName)
		for _, enum := range file.Enums {
			generateEnum(&b, enum)
		}
	} else {
		fmt.Fprintln(&b)
		for _, piece := range file.Pieces {
			switch piece.Kind {
			case parser.PieceGo:
				fmt.Fprint(&b, piece.Text)
			case parser.PieceEnum:
				generateEnum(&b, *piece.Enum)
			}
		}
	}

	rewrite, err := rewriteRuneSyntax(b.Bytes(), file.Enums)
	if err != nil {
		return nil, err
	}

	formatted, err := format.Source(rewrite)
	if err != nil {
		return b.Bytes(), err
	}

	return formatted, nil
}

func enumVariantLookup(enums []parser.Enum) map[string]map[string]string {
	lookup := make(map[string]map[string]string, len(enums))
	for _, enum := range enums {
		variants := make(map[string]string, len(enum.Variants))
		for _, variant := range enum.Variants {
			variants[variant.Name] = enum.Name + variant.Name
		}
		lookup[enum.Name] = variants
	}
	return lookup
}

func enumVariantToEnumLookup(enums []parser.Enum) map[string]string {
	lookup := make(map[string]string, len(enums))

	for _, enum := range enums {
		for _, variant := range enum.Variants {
			lookup[enum.Name+variant.Name] = enum.Name
		}
	}

	return lookup
}

func rewriteRuneSyntax(source []byte, enums []parser.Enum) ([]byte, error) {
	source, runeSwitchBindings, err := preprocessRuneSwitchBinding(source)
	if err != nil {
		return nil, err
	}

	fset := token.NewFileSet()
	file, err := goParser.ParseFile(fset, "", source, goParser.AllErrors|goParser.ParseComments)
	if err != nil {
		return nil, err
	}

	if err := validateNoTypeSwitchSyntax(file, fset); err != nil {
		return nil, err
	}

	enumVariants := enumVariantLookup(enums)
	enumVariantToEnum := enumVariantToEnumLookup(enums)

	ast.Inspect(file, func(node ast.Node) bool {
		switch n := node.(type) {
		case *ast.ExprStmt:
			n.X = rewriteExprInTypeContext(n.X, "", enumVariants, enumVariantToEnum)
		case *ast.AssignStmt:
			for i, rhs := range n.Rhs {
				n.Rhs[i] = rewriteExprInTypeContext(rhs, "", enumVariants, enumVariantToEnum)
			}
		case *ast.CompositeLit:
			if rewrittenType := rewriteRuneTypeExpr(n.Type, enumVariants); rewrittenType != nil {
				n.Type = rewrittenType
			}
		case *ast.TypeAssertExpr:
			if n.Type == nil {
				return true
			}
			if rewrittenType := rewriteRuneTypeExpr(n.Type, enumVariants); rewrittenType != nil {
				n.Type = rewrittenType
			}
		}
		return true
	})

	ast.Inspect(file, func(node ast.Node) bool {
		switch n := node.(type) {
		case *ast.CaseClause:
			for i, expr := range n.List {
				if expr == nil {
					continue
				}
				if rewrittenExpr := rewriteRuneTypeExpr(expr, enumVariants); rewrittenExpr != nil {
					n.List[i] = rewrittenExpr
				}
			}
		}
		return true
	})

	for _, decl := range file.Decls {
		rewriteTopLevelDecl(decl, enumVariants, enumVariantToEnum, map[string]string{}, runeSwitchBindings, fset)
	}

	var out bytes.Buffer
	err = format.Node(&out, fset, file)
	if err != nil {
		return nil, err
	}

	return out.Bytes(), nil
}

func validateNoTypeSwitchSyntax(file *ast.File, fset *token.FileSet) error {
	var err error
	ast.Inspect(file, func(node ast.Node) bool {
		if err != nil {
			return false
		}

		typeSwitch, ok := node.(*ast.TypeSwitchStmt)
		if !ok {
			return true
		}

		if typeAssertExpr := extractTypeAssertFromTypeSwitch(typeSwitch); typeAssertExpr == nil {
			return true
		} else if typeAssertExpr.Type == nil {
			pos := fset.Position(typeAssertExpr.Pos())
			err = fmt.Errorf(
				"parse error at line %d, column %d: `.(type)` is not supported in rune. help: use enum value switch `switch request { case Running: ... }`, or bind once with `switch requestVariant := request { case Running: requestVariant.ID ... }`",
				pos.Line,
				pos.Column,
			)
			return false
		}

		return true
	})
	return err
}

func preprocessRuneSwitchBinding(source []byte) ([]byte, map[int]string, error) {
	re := regexp.MustCompile(`^(\s*)switch\s+([a-zA-Z_][a-zA-Z0-9_]*)\s*:=\s*([^\r\n{]+)\s*\{\s*$`)
	lines := strings.SplitAfter(string(source), "\n")
	bindings := map[int]string{}
	var out strings.Builder

	for i, line := range lines {
		lineNo := i + 1
		lineEnding := ""
		trimmed := strings.TrimSuffix(line, "\n")
		if strings.HasSuffix(line, "\n") {
			lineEnding = "\n"
			trimmed = strings.TrimSuffix(trimmed, "\r")
		}
		if strings.HasSuffix(trimmed, "\r") {
			trimmed = strings.TrimSuffix(trimmed, "\r")
		}
		matches := re.FindStringSubmatch(trimmed)
		if len(matches) == 0 {
			out.WriteString(line)
			continue
		}

		indent := matches[1]
		boundVar := matches[2]
		expr := strings.TrimSpace(matches[3])
		if expr == "" {
			out.WriteString(line)
			continue
		}

		bindings[lineNo] = boundVar
		out.WriteString(indent)
		out.WriteString("switch ")
		out.WriteString(expr)
		out.WriteString(" {")
		out.WriteString(lineEnding)
	}

	return []byte(out.String()), bindings, nil
}

func runeSwitchBindingVar(fset *token.FileSet, s *ast.SwitchStmt, bindings map[int]string) string {
	if len(bindings) == 0 || s == nil || s.Switch == token.NoPos {
		return ""
	}

	line := fset.Position(s.Switch).Line
	return bindings[line]
}

func extractTypeAssertFromTypeSwitch(typeSwitch *ast.TypeSwitchStmt) *ast.TypeAssertExpr {
	if typeSwitch == nil || typeSwitch.Assign == nil {
		return nil
	}

	switch assign := typeSwitch.Assign.(type) {
	case *ast.AssignStmt:
		if len(assign.Rhs) == 0 {
			return nil
		}
		expr, ok := assign.Rhs[0].(*ast.TypeAssertExpr)
		if !ok {
			return nil
		}
		return expr
	case *ast.ExprStmt:
		expr, ok := assign.X.(*ast.TypeAssertExpr)
		if !ok {
			return nil
		}
		return expr
	default:
		return nil
	}
}

func rewriteTopLevelDecl(decl ast.Decl, enumVariants map[string]map[string]string, enumVariantToEnum map[string]string, locals map[string]string, runeSwitchBindings map[int]string, fset *token.FileSet) ast.Decl {
	switch d := decl.(type) {
	case *ast.FuncDecl:
		if d.Body == nil {
			return d
		}

		returnType := ""
		if d.Type != nil && d.Type.Results != nil && len(d.Type.Results.List) > 0 {
			returnType = typeNameFromExpr(d.Type.Results.List[0].Type)
		}

		funcLocals := copyLocals(locals)
		for _, field := range d.Type.Params.List {
			paramType := typeNameFromExpr(field.Type)
			if paramType == "" {
				continue
			}
			for _, name := range field.Names {
				funcLocals[name.Name] = paramType
			}
		}

		d.Body.List = rewriteStmtsWithExpected(d.Body.List, returnType, funcLocals, enumVariants, enumVariantToEnum, runeSwitchBindings, fset)
		return d
	case *ast.GenDecl:
		for _, spec := range d.Specs {
			if valueSpec, ok := spec.(*ast.ValueSpec); ok {
				expectedType := typeNameFromExpr(valueSpec.Type)
				for i, value := range valueSpec.Values {
					valueSpec.Values[i] = rewriteExpr(value, expectedType, enumVariants, enumVariantToEnum)
				}
				for _, name := range valueSpec.Names {
					if name == nil {
						continue
					}
					if expectedType != "" {
						locals[name.Name] = expectedType
					}
				}
			}
		}
		return d
	default:
		return decl
	}
}

func rewriteDeclWithExpectedType(decl ast.Decl, locals map[string]string, enumVariants map[string]map[string]string, enumVariantToEnum map[string]string) ast.Decl {
	switch d := decl.(type) {
	case *ast.GenDecl:
		if d.Tok != token.VAR && d.Tok != token.CONST {
			return decl
		}
		for _, spec := range d.Specs {
			if valueSpec, ok := spec.(*ast.ValueSpec); ok {
				expectedType := typeNameFromExpr(valueSpec.Type)
				for i, value := range valueSpec.Values {
					valueSpec.Values[i] = rewriteExpr(value, expectedType, enumVariants, enumVariantToEnum)
				}
				for _, name := range valueSpec.Names {
					if name == nil {
						continue
					}
					if expectedType != "" {
						locals[name.Name] = expectedType
					}
				}
			}
		}
		return d
	default:
		return decl
	}
}

func rewriteExpr(expr ast.Expr, expectedType string, enumVariants map[string]map[string]string, enumVariantToEnum map[string]string) ast.Expr {
	if expr == nil {
		return nil
	}

	switch e := expr.(type) {
	case *ast.CompositeLit:
		if rewrittenType := rewriteRuneTypeExprWithExpected(e.Type, expectedType, enumVariants); rewrittenType != nil {
			e.Type = rewrittenType
		}

		childExpectedType := typeNameFromCompositeContainer(e.Type)
		isMapLiteral := false
		if _, ok := e.Type.(*ast.MapType); ok {
			isMapLiteral = true
		}
		for i, element := range e.Elts {
			if isMapLiteral {
				if kv, ok := element.(*ast.KeyValueExpr); ok {
					kv.Key = rewriteExpr(kv.Key, "", enumVariants, enumVariantToEnum)
					kv.Value = rewriteExpr(kv.Value, childExpectedType, enumVariants, enumVariantToEnum)
					e.Elts[i] = kv
					continue
				}
			}
			e.Elts[i] = rewriteExpr(element, childExpectedType, enumVariants, enumVariantToEnum)
		}
		return e
	case *ast.CallExpr:
		for i, arg := range e.Args {
			e.Args[i] = rewriteExpr(arg, "", enumVariants, enumVariantToEnum)
		}
		return e
	case *ast.ParenExpr:
		e.X = rewriteExpr(e.X, "", enumVariants, enumVariantToEnum)
		return e
	case *ast.UnaryExpr:
		e.X = rewriteExpr(e.X, "", enumVariants, enumVariantToEnum)
		return e
	case *ast.BinaryExpr:
		e.X = rewriteExpr(e.X, "", enumVariants, enumVariantToEnum)
		e.Y = rewriteExpr(e.Y, "", enumVariants, enumVariantToEnum)
		return e
	case *ast.FuncLit:
		returnType := ""
		if e.Type != nil && e.Type.Results != nil && len(e.Type.Results.List) > 0 {
			returnType = typeNameFromExpr(e.Type.Results.List[0].Type)
		}
		if e.Body != nil {
			litLocals := map[string]string{}
			if e.Type != nil {
				for _, field := range e.Type.Params.List {
					paramType := typeNameFromExpr(field.Type)
					if paramType == "" {
						continue
					}
					for _, name := range field.Names {
						litLocals[name.Name] = paramType
					}
				}
			}
			e.Body.List = rewriteStmtsWithExpected(e.Body.List, returnType, litLocals, enumVariants, enumVariantToEnum, map[int]string{}, nil)
		}
		return e
	case *ast.KeyValueExpr:
		e.Key = rewriteExpr(e.Key, "", enumVariants, enumVariantToEnum)
		e.Value = rewriteExpr(e.Value, "", enumVariants, enumVariantToEnum)
		return e
	case *ast.SliceExpr:
		e.X = rewriteExpr(e.X, "", enumVariants, enumVariantToEnum)
		e.Low = rewriteExpr(e.Low, "", enumVariants, enumVariantToEnum)
		e.High = rewriteExpr(e.High, "", enumVariants, enumVariantToEnum)
		e.Max = rewriteExpr(e.Max, "", enumVariants, enumVariantToEnum)
		return e
	case *ast.IndexExpr:
		e.X = rewriteExpr(e.X, "", enumVariants, enumVariantToEnum)
		e.Index = rewriteExpr(e.Index, "", enumVariants, enumVariantToEnum)
		return e
	default:
		return expr
	}
}

func rewriteExprInTypeContext(expr ast.Expr, expectedType string, enumVariants map[string]map[string]string, enumVariantToEnum map[string]string) ast.Expr {
	return rewriteExpr(expr, expectedType, enumVariants, enumVariantToEnum)
}

func rewriteStmtsWithExpected(stmts []ast.Stmt, expectedReturnType string, locals map[string]string, enumVariants map[string]map[string]string, enumVariantToEnum map[string]string, runeSwitchBindings map[int]string, fset *token.FileSet) []ast.Stmt {
	for i, stmt := range stmts {
		stmts[i] = rewriteStmtWithExpected(stmt, expectedReturnType, locals, enumVariants, enumVariantToEnum, runeSwitchBindings, fset)
	}
	return stmts
}

func rewriteStmtWithExpected(stmt ast.Stmt, expectedReturnType string, locals map[string]string, enumVariants map[string]map[string]string, enumVariantToEnum map[string]string, runeSwitchBindings map[int]string, fset *token.FileSet) ast.Stmt {
	switch s := stmt.(type) {
	case *ast.BlockStmt:
		s.List = rewriteStmtsWithExpected(s.List, expectedReturnType, locals, enumVariants, enumVariantToEnum, runeSwitchBindings, fset)
	case *ast.CaseClause:
		s.Body = rewriteStmtsWithExpected(s.Body, expectedReturnType, locals, enumVariants, enumVariantToEnum, runeSwitchBindings, fset)
	case *ast.CommClause:
		if s.Comm != nil {
			s.Comm = rewriteStmtWithExpected(s.Comm, expectedReturnType, locals, enumVariants, enumVariantToEnum, runeSwitchBindings, fset)
		}
		s.Body = rewriteStmtsWithExpected(s.Body, expectedReturnType, locals, enumVariants, enumVariantToEnum, runeSwitchBindings, fset)
	case *ast.IfStmt:
		if s.Init != nil {
			s.Init = rewriteStmtWithExpected(s.Init, expectedReturnType, locals, enumVariants, enumVariantToEnum, runeSwitchBindings, fset)
		}
		s.Cond = rewriteExpr(s.Cond, "", enumVariants, enumVariantToEnum)
		s.Body = rewriteBlockBodyWithExpected(s.Body, expectedReturnType, locals, enumVariants, enumVariantToEnum, runeSwitchBindings, fset)
		if s.Else != nil {
			s.Else = rewriteStmtWithExpected(s.Else, expectedReturnType, locals, enumVariants, enumVariantToEnum, runeSwitchBindings, fset)
		}
	case *ast.ForStmt:
		if s.Init != nil {
			s.Init = rewriteStmtWithExpected(s.Init, expectedReturnType, locals, enumVariants, enumVariantToEnum, runeSwitchBindings, fset)
		}
		s.Cond = rewriteExpr(s.Cond, "", enumVariants, enumVariantToEnum)
		if s.Post != nil {
			s.Post = rewriteStmtWithExpected(s.Post, expectedReturnType, locals, enumVariants, enumVariantToEnum, runeSwitchBindings, fset)
		}
		s.Body = rewriteBlockBodyWithExpected(s.Body, expectedReturnType, locals, enumVariants, enumVariantToEnum, runeSwitchBindings, fset)
	case *ast.RangeStmt:
		s.X = rewriteExpr(s.X, "", enumVariants, enumVariantToEnum)
		if s.Key != nil {
			s.Key = rewriteExpr(s.Key, "", enumVariants, enumVariantToEnum)
		}
		if s.Value != nil {
			s.Value = rewriteExpr(s.Value, "", enumVariants, enumVariantToEnum)
		}
		s.Body = rewriteBlockBodyWithExpected(s.Body, expectedReturnType, locals, enumVariants, enumVariantToEnum, runeSwitchBindings, fset)
	case *ast.SwitchStmt:
		if s.Init != nil {
			s.Init = rewriteStmtWithExpected(s.Init, expectedReturnType, locals, enumVariants, enumVariantToEnum, runeSwitchBindings, fset)
		}
		s.Tag = rewriteExpr(s.Tag, "", enumVariants, enumVariantToEnum)
		switchExpectedType := inferTypeFromExprWithLocals(s.Tag, locals)
		if s.Body != nil {
			for _, stmt := range s.Body.List {
				clause, ok := stmt.(*ast.CaseClause)
				if !ok {
					continue
				}

				for i, expr := range clause.List {
					if expr == nil {
						continue
					}
					if rewrittenExpr := rewriteRuneTypeExprWithExpected(expr, switchExpectedType, enumVariants); rewrittenExpr != nil {
						clause.List[i] = rewrittenExpr
					}
				}
			}
		}
		if s.Body != nil {
			s.Body.List = rewriteStmtsWithExpected(s.Body.List, expectedReturnType, locals, enumVariants, enumVariantToEnum, runeSwitchBindings, fset)
		}
		if shouldRewriteRuneSwitch(s, switchExpectedType, enumVariants, enumVariantToEnum) {
			assign := ast.Stmt(&ast.ExprStmt{X: &ast.TypeAssertExpr{X: s.Tag}})
			if boundVar := runeSwitchBindingVar(fset, s, runeSwitchBindings); boundVar != "" {
				assign = &ast.AssignStmt{
					Lhs: []ast.Expr{ast.NewIdent(boundVar)},
					Tok: token.DEFINE,
					Rhs: []ast.Expr{&ast.TypeAssertExpr{X: s.Tag}},
				}
			}
			return &ast.TypeSwitchStmt{
				Switch: s.Switch,
				Init:   s.Init,
				Assign: assign,
				Body:   s.Body,
			}
		}
	case *ast.TypeSwitchStmt:
		if s.Init != nil {
			s.Init = rewriteStmtWithExpected(s.Init, expectedReturnType, locals, enumVariants, enumVariantToEnum, runeSwitchBindings, fset)
		}
		s.Body.List = rewriteStmtsWithExpected(s.Body.List, expectedReturnType, locals, enumVariants, enumVariantToEnum, runeSwitchBindings, fset)
	case *ast.LabeledStmt:
		s.Stmt = rewriteStmtWithExpected(s.Stmt, expectedReturnType, locals, enumVariants, enumVariantToEnum, runeSwitchBindings, fset)
	case *ast.SelectStmt:
		s.Body.List = rewriteStmtsWithExpected(s.Body.List, expectedReturnType, locals, enumVariants, enumVariantToEnum, runeSwitchBindings, fset)
	case *ast.ExprStmt:
		s.X = rewriteExpr(s.X, "", enumVariants, enumVariantToEnum)
	case *ast.DeclStmt:
		s.Decl = rewriteDeclWithExpectedType(s.Decl, locals, enumVariants, enumVariantToEnum)
	case *ast.AssignStmt:
		for i, rhs := range s.Rhs {
			s.Rhs[i] = rewriteExpr(rhs, "", enumVariants, enumVariantToEnum)
		}
		if s.Tok == token.DEFINE {
			updateLocalsFromShortDecl(s.Lhs, s.Rhs, locals, enumVariantToEnum)
		}
	case *ast.ReturnStmt:
		for i, result := range s.Results {
			s.Results[i] = rewriteExpr(result, expectedReturnType, enumVariants, enumVariantToEnum)
		}
	}

	return stmt
}

func rewriteBlockBodyWithExpected(block *ast.BlockStmt, expectedReturnType string, locals map[string]string, enumVariants map[string]map[string]string, enumVariantToEnum map[string]string, runeSwitchBindings map[int]string, fset *token.FileSet) *ast.BlockStmt {
	if block == nil {
		return nil
	}
	block.List = rewriteStmtsWithExpected(block.List, expectedReturnType, locals, enumVariants, enumVariantToEnum, runeSwitchBindings, fset)
	return block
}

func copyLocals(in map[string]string) map[string]string {
	copied := make(map[string]string, len(in))
	for key, value := range in {
		copied[key] = value
	}
	return copied
}

func inferTypeFromExprWithLocals(expr ast.Expr, locals map[string]string) string {
	if expr == nil {
		return ""
	}

	switch e := expr.(type) {
	case *ast.Ident:
		if locals == nil {
			return ""
		}
		return locals[e.Name]
	case *ast.ParenExpr:
		return inferTypeFromExprWithLocals(e.X, locals)
	default:
		return ""
	}
}

func inferTypeFromExpr(expr ast.Expr, locals map[string]string) string {
	if expr == nil {
		return ""
	}

	if id := inferTypeFromExprWithLocals(expr, locals); id != "" {
		return id
	}

	switch e := expr.(type) {
	case *ast.CompositeLit:
		return typeNameFromExpr(e.Type)
	case *ast.BasicLit, *ast.CallExpr, *ast.UnaryExpr, *ast.BinaryExpr, *ast.ParenExpr:
		return ""
	default:
		return ""
	}
}

func updateLocalsFromShortDecl(lhs []ast.Expr, rhs []ast.Expr, locals map[string]string, enumVariantToEnum map[string]string) {
	if len(lhs) != len(rhs) || locals == nil {
		return
	}

	for i, lhsExpr := range lhs {
		name, ok := lhsExpr.(*ast.Ident)
		if !ok {
			continue
		}
		if name.Name == "" {
			continue
		}

		inferred := inferTypeFromExpr(rhs[i], locals)
		if inferred != "" {
			locals[name.Name] = inferred
			continue
		}

		variantName := inferVariantFromCompositeType(rhs[i], enumVariantToEnum)
		if variantName != "" {
			locals[name.Name] = variantName
		}
	}
}

func inferVariantFromCompositeType(expr ast.Expr, enumVariantToEnum map[string]string) string {
	composite, ok := expr.(*ast.CompositeLit)
	if !ok {
		return ""
	}

	ident, ok := composite.Type.(*ast.Ident)
	if !ok {
		return ""
	}

	return enumVariantToEnum[ident.Name]
}

func typeNameFromExpr(expr ast.Expr) string {
	switch t := expr.(type) {
	case *ast.Ident:
		return t.Name
	case *ast.ParenExpr:
		return typeNameFromExpr(t.X)
	case *ast.StarExpr:
		return typeNameFromExpr(t.X)
	default:
		return ""
	}
}

func typeNameFromCompositeContainer(expr ast.Expr) string {
	switch e := expr.(type) {
	case *ast.ArrayType:
		return typeNameFromExpr(e.Elt)
	case *ast.MapType:
		return typeNameFromExpr(e.Value)
	default:
		return ""
	}
}

func shouldRewriteRuneSwitch(s *ast.SwitchStmt, expectedType string, enumVariants map[string]map[string]string, enumVariantToEnum map[string]string) bool {
	if s.Tag == nil || s.Body == nil {
		return false
	}

	var enumName string
	for _, stmt := range s.Body.List {
		clause, ok := stmt.(*ast.CaseClause)
		if !ok {
			continue
		}

		for _, expr := range clause.List {
			if expr == nil {
				continue
			}
			ident, ok := expr.(*ast.Ident)
			if !ok {
				selector, ok := expr.(*ast.SelectorExpr)
				if !ok {
					return false
				}
				rewritten := rewriteRuneTypeExpr(selector, enumVariants)
				if rewritten == nil {
					return false
				}
				qualifiedExpr, ok := rewritten.(*ast.Ident)
				if !ok {
					return false
				}
				mapped, ok := enumVariantToEnum[qualifiedExpr.Name]
				if !ok {
					return false
				}
				if enumName == "" {
					enumName = mapped
				} else if enumName != mapped {
					return false
				}
				continue
			}

			if expectedType != "" {
				variants, ok := enumVariants[expectedType]
				if !ok {
					return false
				}
				variantName := ident.Name
				_, isBare := variants[variantName]
				if !isBare && strings.HasPrefix(variantName, expectedType) {
					variantName = strings.TrimPrefix(variantName, expectedType)
				}
				if _, ok := variants[variantName]; !ok {
					return false
				}
				if enumName == "" {
					enumName = expectedType
				} else if enumName != expectedType {
					return false
				}
				continue
			}

			mapped, ok := enumVariantToEnum[ident.Name]
			if !ok {
				return false
			}
			if enumName == "" {
				enumName = mapped
			} else if enumName != mapped {
				return false
			}
		}
	}

	return enumName != ""
}

func rewriteRuneTypeExpr(expr ast.Expr, enumVariants map[string]map[string]string) ast.Expr {
	switch e := expr.(type) {
	case *ast.SelectorExpr:
		enumName, ok := e.X.(*ast.Ident)
		if !ok {
			return nil
		}

		variants, ok := enumVariants[enumName.Name]
		if !ok {
			return nil
		}

		qualified, ok := variants[e.Sel.Name]
		if !ok {
			return nil
		}
		return ast.NewIdent(qualified)
	default:
		return nil
	}
}

func rewriteRuneTypeExprWithExpected(expr ast.Expr, expectedType string, enumVariants map[string]map[string]string) ast.Expr {
	if rewritten := rewriteRuneTypeExpr(expr, enumVariants); rewritten != nil {
		return rewritten
	}

	if expectedType == "" {
		return nil
	}

	variants, ok := enumVariants[expectedType]
	if !ok {
		return nil
	}

	ident, ok := expr.(*ast.Ident)
	if !ok {
		return nil
	}

	qualified, ok := variants[ident.Name]
	if !ok {
		return nil
	}

	return ast.NewIdent(qualified)
}

func generateEnum(b *bytes.Buffer, enum parser.Enum) {
	fmt.Fprintf(b, "type %s interface {\n", enum.Name)
	fmt.Fprintf(b, "\tis%s()\n", enum.Name)
	fmt.Fprintf(b, "}\n\n")

	for _, variant := range enum.Variants {
		generateVariant(b, enum, variant)
	}
}

func generateVariant(b *bytes.Buffer, enum parser.Enum, variant parser.Variant) {
	structName := enum.Name + variant.Name

	if len(variant.Fields) == 0 {
		fmt.Fprintf(b, "type %s struct{}\n\n", structName)
	} else {
		fmt.Fprintf(b, "type %s struct {\n", structName)

		for _, field := range variant.Fields {
			fmt.Fprintf(b, "\t%s %s\n", field.Name, field.Type)
		}

		fmt.Fprintln(b, "}")
		fmt.Fprintln(b)
	}

	fmt.Fprintf(b, "func (%s) is%s() {}\n\n", structName, enum.Name)

	generateConstructor(b, enum, variant)
}

func generateConstructor(b *bytes.Buffer, enum parser.Enum, variant parser.Variant) {
	structName := enum.Name + variant.Name
	funcName := "New" + structName

	params := make([]string, 0, len(variant.Fields))
	assignments := make([]string, 0, len(variant.Fields))

	for _, field := range variant.Fields {
		paramName := lowerFirst(field.Name)

		params = append(params, fmt.Sprintf("%s %s", paramName, field.Type))
		assignments = append(assignments, fmt.Sprintf("%s: %s", field.Name, paramName))
	}

	fmt.Fprintf(b, "func %s(%s) %s {\n", funcName, strings.Join(params, ", "), enum.Name)

	if len(assignments) == 0 {
		fmt.Fprintf(b, "\treturn %s{}\n", structName)
	} else {
		fmt.Fprintf(b, "\treturn %s{%s}\n", structName, strings.Join(assignments, ", "))
	}

	fmt.Fprintln(b, "}")
	fmt.Fprintln(b)
}

func lowerFirst(s string) string {
	if s == "" {
		return s
	}

	return strings.ToLower(s[:1]) + s[1:]
}
